insecureServing:
  bindPort: 8080
  enabled: true

secureServing:
  enabled: false

authentication:
  oidc:
    caFile: ./testdata/openid.crt
    clientID: my-client
    issuerURL: https://localhost:8443
    usernameClaim: username
    groupsClaim: groups
