insecureServing:
  bindPort: 8080
  enabled: true

secureServing:
  enabled: false

authentication:
  tokenAuthFile: ./tokens.cvs

authorization:
  modes:
  - Webhook
  webhookConfigFile: ./client.conf
