secureServing:
  bindPort: 8443
  serverCert:
    certDir: ./testdata
    pairName: server

authentication:
  requestheader:
    clientCAFile: ./testdata/ca.crt
    usernameHeaders: ["x-remote-user"]
    groupHeaders: ["x-remote-group"]
    extraHeaderPrefixes: ["x-remote-extra-"]
