insecureServing:
  bindPort: 8080
  enabled: true

secureServing:
  enabled: false

authentication:
  anonymous: true
  tokenAuthFile: ./tokens.cvs

authorization:
  modes:
  - RBAC
  rbacConfigDir: ./testdata
