logging:
  verbosity: 10

apiserver:
  insecureServing:
    bindAddress: 0.0.0.0
    bindNework: tcp
    bindPort: 8080
    enabled: true
  secureServing:
    enabled: false
  # for swagger
  securitySchemes:
    - name: BaseAuth
      type: base

authentication:
  anonymous: false
  tokenAuthFile: ./tokens.cvs

authorization:
  modes:
  - RBAC
  rbac:
    configPath: ./testdata
