insecureServing:
  enabled: false

secureServing:
  enabled: true
  bindPort: 8443
  serverCert:
    certDir: ../testdata/
    pairName: openid

oidc-provider:
  rsakey: "../testdata/rsa.pem"
  openIDConfig: |
    {
      "issuer": "https://localhost:8443",
      "jwks_uri": "https://localhost:8443/.testing/keys"
    }
  claim: |
    {
      "iss": "https://localhost:8443",
      "aud": "my-client",
      "username": "steve",
      "groups": ["team1", "team2"],
      "exp": %d
    }


