insecureServing:
  bindPort: 8080
  enabled: true

secureServing:
  enabled: false

authentication:
  anonymous: false
  tokenAuthFile: ./tokens.cvs

authorization:
  modes:
  - ABAC
  policyFile: ./abac.json
