insecureServing:
  bindPort: 8080
  enabled: true
secureServing:
  enabled: false

s3:
  endpoint: 127.0.0.1:9000
  accessKeyID: "fw8LrYkEP0lRjMb7"
  secretAccessKey: "0u57StTemDncw7YQ4RX7yCnzH4mchwbS"
  bucketName: test
  tls:
    insecure: true
    #insecureSkipVerify: true
    #caFile: ./testdata/ca.crt
